### ISSUE TITLE
Related to https://github.com/cesarvarela/subway-hardhat

### ISSUE THREAD

**Issue by crypt0inf0** [cesarvarela/cesarvarela.com#24]
Hi, I'm posting this here because I don't know how to contact you.

First of all thanks for porting https://github.com/libevm/subway to typescript & I used it on testnet but does it can handle the high frequency trade requests placed on pancakeswap?

As you know there are multiple bots competing against each other does typescript can handle it? 

Or Is there's a plan to port it to GOLANG in the future for better performance?

Thanks

**Comment by cesarvarela** [comment]
This is for learning purposes only (I'm trying to get into web3 development); it probably gets rekt on the mainnet.

Please don't trust anyone who gives a profitable bot away for free; there are many scams.
